### ISSUE TITLE
Petites améliorations

### ISSUE THREAD

**Issue by chreggy** [revlysJ/jeedouino#1]
Bonjour,

j'aurais des suggestions d'améliorations du plugin concernant principalement l'utilisation des I/O des Arduino : 

- Est-ce qu'il serait possible d'ajouter aux entrées analogiques A0-A5 le statut "Entrée numérique" avec/sans PULL-UP" ?
J'ai été obligé de créer des PIN utilisateurs pour faire çà alors que les PIN A0-A5 peuvent très bien fonctionner en mode digital de D14 à D19.

- L'Arduino Nano possède 2 PIN A6-A7 supplémentaires qui ne fonctionnent elles qu'en analogique mais elles ne sont pas dispo.

En tout cas, bravo pour ce super plugin qui offre déjà beaucoup de possibilités :o)

**Comment by revlysJ** [comment]
Bonjour,

Désolé pour la réponse tardive.
Merci pour les suggestions, je me les notes.

Cordialement.
