### ISSUE TITLE
problème génération sketch en local

### ISSUE THREAD

**Issue by belgotux** [revlysJ/jeedouino#17]
Hello,

J'ai remarqué un souci lors de la génération de sketch en local en usb pour un arduino nano. Jeedouino laisse une ligne liée à une génération réseau.
Dans mon cas une sonde DS18B20 et une entrée numérique à générer et la ligne suivante dans le sketch est à supprimer en L505 : 
`client.print(F("SOK"));												// On reponds a JEEDOM`

Dans cette partie du code : 
```
			else if (c[0]=='S' && c[n]=='P')		 	// Reçoi le délai de relève des sondes
			{
				if (n > 1)										// Petite securite
				{
					for (int i = 1; i < n; i++)
					{
						if (isDigit(c[i])) c[i] = c[i] - '0';
					}

					int multiple = 1;
					pinTempo = 0;
					for (int i = n-1; i > 0; i--)										// récupération de la valeur
					{
						pinTempo += int(c[i]) * multiple;
						multiple *= 10;
					}
					if (pinTempo < 1 || pinTempo > 1000) pinTempo = 5;
					ProbePauseDelay = 60000 * pinTempo;

					client.print(F("SOK"));												// On reponds a JEEDOM
					jeedom+=F("&REP=SOK");
				}
			}
```
Super projet en tout cas!

**Comment by revlysJ** [comment]
Bonjour,

Merci pour le retour.

Le souci est corrigé en beta (commit d5e92b53bef301383983ff35cb8667a634a74bb1).
Il faut remplacer la ligne en question par :
`Serial.println(F("SOK"));`

Bonne journée.
