### ISSUE TITLE
fonctionnement du plugin RPI distant

### ISSUE THREAD

**Issue by bananavdk** [revlysJ/jeedouino#19]
bonjour,
d'abord merci pour tout ce que tu fait, j'utilise déjà ce plugin pour piloter le ventilateur de ma baie télécom a l'aide d'un relais et d'une sonde DS18B20 sur arduino nano puisque j'utilise un NUC et franchement c'est super stable bravo.

aujourd'hui je cherche a récupérer des info binaire sur un raspberry distant (pas celui de mon jeedom) j'ai installé magic mirror2 et j'aimerais récupérer une info de mouvement avec un capteur PIR afin d'allumer et éteindre l'ecran
 j'ai lut au cour de mes recherches qu'il fallait installer un autre jeedom sur le pi.
Est-ce vais ?
si non quelle est la marche a suivre je n'ai rien trouvé dans la doc du plugin si ce n'est l'installation de wiringpi (je suppose sur le pi distant).

d'avance merci.

**Comment by revlysJ** [comment]
Bonjour,

Cette question a plus sa place sur le forum community de jeedom, ici c'est plutôt pour les bugs.
Tu peux installer un autre jeedom sur le pi distant, ce serai le plus simple.
Sinon, tu peux aussi utiliser l'option jeedouinoExt du plugin si tu es à l'aise avec les commandes linux, car il faudra surement l'installer à la main via ssh.

Bonne journée.

**Comment by bananavdk** [comment]
Merci de ta réponse je pensais pouvoir trouvé de l'aide ici comme c'est le cas pour le plugin abeille.
Effectivement j'ai réussi à installer la version ext sans jeedom et sa fonctionne nickel néanmoins une petite MAJ de la doc du plug-in sur cette option serait la bien venue.
