### ISSUE TITLE
Entrée analogique : possible d'appliquer une transformation ?

### ISSUE THREAD

**Issue by mnapoli** [revlysJ/jeedouino#2]
Bonjour ! Je suis en train de bricoler une connexion entre mon arduino et mon raspberry pi pour remonter la valeur d'un capteur de température. Du coup je suis tombé sur ce plugin qui m'économiserait du boulot, ça a l'air cool !

Cependant j'ai beau lire la documentation je n'arrive pas à savoir si il est possible d'appliquer une transformation (un calcul) à une valeur d'une entrée analogique ?

En gros voici le code Arduino qui lit depuis l'entrée analogique : 

```c
 int reading = analogRead(sensorPin);  
 
 // converting that reading to voltage
 float voltage = reading * 5.0;
 voltage /= 1024.0; 
 
 // now print out the temperature
 float temperatureC = (voltage - 0.5) * 100 ;  //converting from 10 mv per degree wit 500 mV offset
                                               //to degrees ((voltage - 500mV) times 100)
```

Au final j'ai la température en degrés. Mais comme le plugin lit directement la valeur depuis l'entrée analogique je ne suis pas sur de pouvoir répliquer ce calcul avec jeeduino.

Possible ?

**Comment by revlysJ** [comment]
Bonjour,

Désolé pour la réponse tardive.
Vous pouvez utiliser les pins utilisateurs pour intégrer votre code.
Il me semble que des exemples ont été partagés sur le forum dans le fil du plugin.

Cordialement.
