### ISSUE TITLE
Exception on serial dependency

### ISSUE THREAD

**Issue by laurent-dumestier** [revlysJ/jeedouino#20]
Hello

When dependency serial is in error : 

![image](https://user-images.githubusercontent.com/4517935/104714307-59630480-5725-11eb-8785-b720f4ac4f3d.png)

How to solve : 
Replace SimpleSend('&NODEP = SERIAL') with SimpleSend('&NODEP=SERIAL')

This error happened for me when serial is installed by another module after jeedouino :
![image](https://user-images.githubusercontent.com/4517935/104714498-90391a80-5725-11eb-8265-ddee4124d8f2.png)

Maybe add in error message to check that serial is not installed, because is in conflict with pyserial.

Great work on this plugin

Regards

**Comment by revlysJ** [comment]
Hello,

Nice catch!
Thanks you for this report. 
I will correct it asap.

Regards.
