### ISSUE TITLE
GPIO is setup with GPIO.PUD_DOWN if Status_pins is 'p'

### ISSUE THREAD

**Issue by mick111** [revlysJ/jeedouino#23]
Bonjour, dans le cas ou je souhaite configurer mon Raspberry PI / JeedouinoExt en entree numérique avec pull up, la config se fait en pull down indépendamment du fait que Status_pins soit en 'i' ou 'p'
https://github.com/revlysJ/jeedouino/blob/c72ff4ca06e27ab5ff3d31e9fd60756a675dc834/ressources/jeedouinoPiGpio.py#L896

**Comment by mick111** [comment]
```python
GPIO.setup(j, GPIO.IN,  pull_up_down=GPIO.PUD_DOWN if Status_pins[i - 1] == 'i' else GPIO.PUD_UP)
```

**Comment by revlysJ** [comment]
Bien vu !
Merci.

**Comment by mick111** [comment]
Avec plaisir !

Merci à vous pour le boulot
