### ISSUE TITLE
Problème de réutilisation d'un microcontroleur dans nouvel équipement

### ISSUE THREAD

**Issue by casam4** [revlysJ/jeedouino#29]
Lorsque j'ai utilisé un microcontroleur avec un équipement. Il est ensuite impossible de le ré-utiliser dans un nouvel équipement. J'ai créer un nouvel équipement avec une nouvelle adresse ip et flasher le microcontrolleur avec le sketch du nouvel équipement, Jeedom n'arrive pas à communiquer avec le microcontrolleur (error: no route to host) alors que je ping l'adresse ip avec succès avec le plugin network. Ensuite j'ai régulièrement des message qui disent Equipement not found avec l'id de l'équipement précédent. C'est comme s'il gardait l'id de l'équipement précédent en mémoire même après avoir été reflashé avec un nouveau sketch. Est-ce possible de re-initialiser le EqID. 

Il est impossible d'attribuer un adresse ip fixe choisie soi-même en mettant "#define NODHCP" sur 1

J'espère ne pas avoir été trop confus dans mes explications. Merci beaucoup pour le travail fait sur ce plugin

**Comment by revlysJ** [comment]
Bonsoir,

Si l'arduino est flashé, connecté au réseau et qu'il réponds au ping sur son ip, alors il faut aller sur l'équipement Jeedouino correspondant et :
- Vérifier que l'ip renseignée est bien celle de l'arduino, si non la mettre à jour.
- Cliquer sur Sauver / Générer pour que la nouvelle configuration (dont l'eqId) soit envoyée à l'arduino.

Bonne soirée.

**Comment by revlysJ** [comment]
AutoClose
