### ISSUE TITLE
double pulse

### ISSUE THREAD

**Issue by bobdivx** [revlysJ/jeedouino#3]
bonjour, 
je dispose d'une serrure Sherlock S2 avec telecommande bluetooth, celle-ci est reluier a mon rpi, le tout bien configurer sur jeedouino.

mon probleme: pour déverouiller la serreure il faut faire un double appuis sur le bouton, avec une intervalle normal ( comme un  double click sur une souris)

le probleme c'est que je ne c'est pas comment configurer ce "double-pulse" 

merci d'avance

**Comment by revlysJ** [comment]
Bonjour,

Désolé pour la réponse tardive.
Pour l'instant, il faut utiliser un scénario pour faire cela.
Je me note l'idée du double-pulse. Merci.

Cordialement.
