### ISSUE TITLE
Bug fonction send lcd16x2

### ISSUE THREAD

**Issue by ghbillou2** [revlysJ/jeedouino#31]
Bonjour,
Il semble avoir une erreur avec la fonction send LCD. Dans le code jeedonuioUSB.py, il manque dans le cmd_list le retour de SMOK

Merci pour ton code

**Comment by revlysJ** [comment]
Bonjour,

Bien vu !

Merci.

**Comment by ghbillou2** [comment]
De rien
Si cela t'intéresse, j'ai rajouté l'arduino Leonardo avec le 32u4. Et j'ai
un autre bug sur le sketck USB ino. Pour l'instant j'arrive pas à trop
comprendre, mais pour le résoudre j'ai désactiver la partie init_eeprom.

Bonne soirée

**Comment by revlysJ** [comment]
Bonjour,

Désolé pour la réponse tardive.
Je veux bien ton ajout pour le leonardo.
Tu peux m'en dire plus sur ton souci avec le sketch usb ?

Bonne journée.
