### ISSUE TITLE
Arduino - PIN en input_pullup - Le mode INPUT_PULLUP semble ne pas être actif

### ISSUE THREAD

**Issue by csphoenix1** [revlysJ/jeedouino#33]
Hello,

Les PIN configurés via Jeedom en INPUT_PULLUP semblent ne pas être configurées comme telle.

En effet, si je connecte le PIN 2 à GND, l'état passe bien à 0.
Si je débranche le PIN 2 de GND, l'état passe bien à 1.
En revanche, sans faire aucune action, je constate que l'état se met à bagotter entre 1 et 0. Comme s'il n'y avait pas le mode PULLUP.

Maintenant, si dans le SKETCH j'ajoute "pinMode(i, INPUT_PULLUP);" sous la ligne "case 'p':    // input_pullup", alors je n'ai plus de bagotement et l'état reste bien à 1 (plus de problème de parasite).

Est-ce un oubli ?

Merci :)

**Comment by revlysJ** [comment]
Bonjour,

Bien vu et merci pour le retour !
Pas un oubli mais un malheureux couper - coller  lors d'une modif précédente ;-(

Bonne journée.

**Comment by csphoenix1** [comment]
Hello,

Ravi d'avoir pu apporter ma patte à ton super projet :)

Bonne continuation et meilleurs voeux.
