### ISSUE TITLE
Détails sur la communication entre démon arduino et la carte

### ISSUE THREAD

**Issue by glt248** [revlysJ/jeedouino#39]
Bonjour,

Je suis actuellement en train de tester le plugin avec des cartes Arduino, mais je rencontre des problèmes assez basiques comme :
- Après configuration de l'ensemble, la carte répond au démon, mais rien ne se passe.
- pas de retour d'état de broches.

J'essaie simplement de faire un blink avec la led présente sur toute carte Arduino.

Pour essayer de voir d'où vient le problème, j'ai commencé à reprendre le code du sketch de base, en le réorganisant pour simplifier la lecture et la maintenance future.

Je cherche les détails de communication, c'est-à-dire :
- la liste des commandes exhaustives lancées par le démon
- y a-t-il des publications de la carte vers le démon sans requêtes préalables ? (Publication périodique de l'état des broches ?)
- Quel est l'ordre d'envoi de requête pour l'initialisation de la communication ?

Je n'y connais pas grand-chose en php, et peu en python, mais j'ai un bon baguage en programmation embarquée (microcontrôleurs).
J'ai lu la doc, qui explique les différentes configurations possibles, mais je n'ai rien trouvé sur le protocole d'échange. Ai-je loupé une page ?

Très naturellement,

**Comment by alibaba080290** [comment]
Bonjour,
J'ai le même problème que toi, j'ai installé Jeedom sur un Pi3b+, Jeedouino pour faire fonctionner une arduino Mega.
Installation + paramètrage du plug-in, déclaration des pins et sauvegarde, installation des librairies et du sketch à partir de IDE arduino. Installation des dépendances et démons ok... quand j'essaye d'activer les sorties, l'arduino clignote mais la sortie reste bloquée à 3.6v peu importe la commande.

**Comment by glt248** [comment]
Bonjour, je suis passé sur home assistant, l'ensemble fonctionne beaucoup mieux et est 100% open source. Bonne continuation.
