### ISSUE TITLE
Debian Buster compatibility

### ISSUE THREAD

**Issue by benoit-cty** [revlysJ/jeedouino#4]
When using Jeedouino on Debian 10 Buster (with a fresh install on Rpi3), the page of the plug-in did not show up, only the menu bar. Error 500 on calling "/index.php?v=d&m=jeedouino&p=jeedouino"
But nothing /var/www/html/log/http.error

On the Jeedom forum someone said that it's a Buster compatibility problem.

I made a new install on Debian 9 Strech and it's OK.

If you give me more info, maybe I could help.

Thanks for this very useful plugin !

**Comment by revlysJ** [comment]
Hi,

This is a PHP 7.2+ problem. They modified the use of the object class.

You can resolve this by updating two lines of code in :
/var/www/html/plugins/jeedouino/desktop/modal/conf_pin.php (line 262) and
/var/www/html/plugins/jeedouino/desktop/php/jeedouino.php (line 160)
Search for `foreach (object::all() as $object)` and replace by `foreach (jeeObject::all() as $object)`
That's it.

Yours.
