### ISSUE TITLE
Set d'un pin TéléInfo en TX qui écrase la configuration RX ?

### ISSUE THREAD

**Issue by dough29** [revlysJ/jeedouino#40]
Salut,

Je suis en train de basculer ma téléinfo Linky depuis un Arduino + mySensors vers un Wemos D1 Mini.

Dans le sketch on a :

https://github.com/revlysJ/jeedouino/blob/4befca301cf2c8988b6fe305be53f7c3f49feb73/sketchs/JeedouinoESP.ino#L1562-L1571

Il me semble que dans la configuration on donne la même valeur pour le pin RX et le pin TX : cela ne va pas du coup mettre le pin en mode "OUTPUT" alors qu'on l'attend en mode "INPUT" 🤔

En tout cas en l'état ça ne semble pas fonctionner pour moi.

Merci pour le boulot en tout cas, c'est surtout agréable à utiliser 👍

**Comment by revlysJ** [comment]
Bonjour,

J'ai corrigé (j'espère) un bug en ce sens dans la beta.
Par contre, je n'ai plus le matériel nécessaire pour tester la teleinfo.

Bonne journée.

**Comment by dough29** [comment]
Salut, merci pour le patch !

J'ai aussi migré mes protocoles donc plus de matériel pour valider 😬

**Comment by revlysJ** [comment]
Ok, tant pis alors...
