### ISSUE TITLE
affichage bizarre avec jeedom 4.4....

### ISSUE THREAD

**Issue by richard0736-jeedom** [revlysJ/jeedouino#41]
Bonjour,
je ne comprends pas, depuis la version de jeedom 4.4 le plugin réagit d’une manière étrange. Quand je vais sur un équipement dès que j’essaie d’aller sur un onglet (équipement, commande, pin…) l’affichage bascule sur dans une barre avec le nom de l’équipement et en dessous les commandes avec la coche dans afficher.
Est-il possible de corriger le problème ?
Il me semble que le plugin ne connaît plus de MAJ, est-il obsolète ? Si oui c’est bien dommage et par lequel vais-je le remplacer si c’est possible ?
Merci par avance
Cordialement
Richard

Copie d’écran de l’affichage quand on est dans l’équipement
[jeeduino.pdf](https://github.com/user-attachments/files/16551742/jeeduino.pdf)

**Comment by Cyrilinf1** [comment]
Bonjour

Effectivement ca fait quelques temps que j'ai aussi le problème. Il est impossible de toucher à la conf du plugin car une page des "résultats" vient par dessus la page de conf.
J'ai ouvert un incident coté Jeedom mais comme je le pensais pour eux c'est le plugin et ils ne le gèrent pas donc pas besoin de chercher de ce coté la. Le plugin n'a pourtant pas été mis à jour depuis longtemps et c'est bien lors d'une maj de Jeedom que c'est arrivé donc pas la faute de Jeedom je sais pas mais c'est bien un changement de comportement de jeedom qui fait bugguer le plugin.

Pourquoi je suis dans les datacenters et pas du coté des dev ... ca m'aurait bien servi.

Je pense revenir sur une ancienne version de Jeedom car ma maison ne peut pas fonctionner sans ce superbe plugin.
J'ai un arduino coté chaufferie qui gère le chauffage les panneaux solaires thermiques l'eau chaude sanitaire la piscine
Un autre relié au chargeur solaire et onduleur qui gère la batterie de la maison la charge des voitures selon la puissance solaire le delestage ...
Un autre dans le salon ...
Bref j'en ai mis partout et tout dépend donc de Jeedom et de ce plugin. Il n'y a pas de plugin "concurrent"  et jeedom ne compte pas en créer un, pour eux ca coutent plusieurs dizaines de milliers d'euros pour peu demande dans ce cas.

Si quelqu'un veut prendre le relai de revlys ou lui même pour nous débloquer (meme en passant le plugin payant) je serai preneur.

**Comment by revlysJ** [comment]
Bonjour,

J'ai fait quelques modifs sur la beta qui devraient (j'espère) corriger ce problème d'affichage.

Bonne journée.

**Comment by Cyrilinf1** [comment]
Bonjour
Je confirme que en béta l'affichage reste bien sur la page de configuration des commandes et ne saute plus vers le "résultat" de ces commandes. 
Merci beaucoup pour cette modification, j'avoue avoir eu quelques sueurs froides en ne pouvant plus utiliser ce plugin et avoir commencé a regarder pour tout passer en mqtt, mais c'est pas si simple même si c'est faisable

Encore merci
Bonne journée

**Comment by richard0736-jeedom** [comment]
Bonjour,
70 ans + mal à la tête, comment fait-on pour avoir la version Beta, tout du moins la recharger sans tout casser ?
Merci pour votre patience
Richard

**Comment by Cyrilinf1** [comment]
En allant dans le site market jeedom sur votre profil il y a une ça se à cocher
Ensuite dans jeedom market vous cherchez jeedouino et vous aurez 2 possibilité, install stable ou install beta
________________________________

**Comment by Cyrilinf1** [comment]
Bonjour, j'étais passé sur le beta et jeedouino n'avait plus le problème. En revanche depuis mon jeedom s'arrêtait sans explication. J'ai supprimé tous les logs dans jeedom pour essayer de trouver mais quand je le redémarré tout était en vert.
Hier soir je revenu sur la version stable et il a tenu jusqu'à maintenant sans s'arreter.
Il y a peut etre un problème dans la beta ou dans mon jeedom (ce n'est pas à exclure).
C'est un smart réinstallé avec debian 11.

Pour moi ca n'est pas un "probleme", je ne touche pas à la conf jeedouino tous les jours et passer de la stable à la beta se fait facilement. J'ai cru comprendre aussi que si je debranchais mes arduino quand je veux modifier la conf je peux le faire avec la version stable car étant hors ligne ils ne revnoient pas d'infos et je peux rester sur le panneau conf.

Bonne journée

**Comment by revlysJ** [comment]
Bonjour,

La version stable du plugin contient les correctifs d'affichage (et d'autres bricoles) donc plus besoin d'utiliser la beta pour l'instant.
Concernant l'arrêt intempestif de Jeedom, je n'ai pas constaté ce phénomène de mon coté. A surveiller.

Bonne journée.
