### ISSUE TITLE
Pin States (Last Update)

### ISSUE THREAD

**Issue by Boyington91** [revlysJ/jeedouino#6]
Since new update (2019-09-14 09:13:31) i'm not able to retrieve state of Pin

[jeedouino.txt](https://github.com/revlysJ/jeedouino/files/3613976/jeedouino.txt)
[jeedouino_update.txt](https://github.com/revlysJ/jeedouino/files/3613977/jeedouino_update.txt)

**Comment by revlysJ** [comment]
Hi,

This is NOT an update, Jeedom put Updates even when they make a translate of the doc.

The error you have is because your network is unreachable. It's in the logs.

Yours.

**Comment by Boyington91** [comment]
Sorry didn't see this in my log
Do you know how to resolve this issue ? Which parameter is not set correctly ?
Thanks

**Comment by revlysJ** [comment]
>Sorry didn't see this in my log
>Do you know how to resolve this issue ? Which parameter is not set correctly ?
>Thanks

Hard to guess.
Verify your network wiring.
Restart your Jeedom then check for it's ip internal settings.
Then look at your jeedouino equipements and check if their ip settings matches jeedom's ip.
Yours.
